<a href="https://colab.research.google.com/github/lima-breno/deep_learning_frameworks/blob/main/frameworks_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **FRAMEWORKS DE DEEPLEARNING**
# **Prática - PyTorch**

**Descrição**: Este notebook apresenta uma introdução ao framework PyTorch.

In [ ]:
import torch

In [ ]:
torch.__version__

'2.6.0+cu124'

In [ ]:
#Criando um tensor (classe tensor)

torch.Tensor([1,2,3]) #posso colocar uma lista de inteiros, mas ele converte para float32 automaticamente com o "Tensor"


tensor([1., 2., 3.])

In [ ]:
#posso criar um tensor com array do numpy
import numpy as np
np.array([1,2,3])

#convertendo
tensor_1 = torch.Tensor(np.array([1,2,3]))
tensor_1

tensor([1., 2., 3.])

 ## **Tipos de Tensores**

In [ ]:
tensor_1.dtype

torch.float32

In [ ]:
#criando um tensor com int

torch.IntTensor([1,2,3])
#ja aparece como int

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
#criando um tensor como booleano (0 é falso, tudo que é dif de zero é verdadeiro)

torch.BoolTensor([1,0,3, True])


tensor([ True, False,  True,  True])

In [ ]:
tensor_2 = torch.rand(1,2) # num aleatorios em 1 lin e duas col
tensor_2

tensor([[0.3097, 0.9087]])

In [ ]:
tensor_2.shape

torch.Size([1, 2])

 ## **Conversão entre tipos de tensores**

In [ ]:
#chamo o metodo com o nome que eu quero converter
#converter o tensor_1 (float) para int
tensor_1.int()

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
#conversao para booleano
tensor_1.bool()

tensor([True, True, True])

In [ ]:
#existem diversos tipode de tensores, legal seria acessar a biblioteca do pytorch para poder identificá-los

 ## **Operações**

In [ ]:
tensor_a = torch.Tensor([1, 2, 3])
tensor_b = torch.Tensor([4, 5, 6])

####**Adição**

In [ ]:
tensor_a + tensor_b

tensor([5., 7., 9.])

####**Subtração**

In [ ]:
tensor_a - tensor_b

tensor([-3., -3., -3.])

####**Multiplicação**

In [ ]:
tensor_a * tensor_b

tensor([ 4., 10., 18.])

####**Divisão**

In [ ]:
tensor_a / tensor_b

tensor([0.2500, 0.4000, 0.5000])

####**Vetores com tamanhos diferentes**

Não rola! ambos tem que ter as mesmas dimensões

In [ ]:
tensor_a + torch.Tensor([1,2,3,4,5,6,7])

RuntimeError: The size of tensor a (3) must match the size of tensor b (7) at non-singleton dimension 0

##**Operações Matriciais**

In [ ]:
tensor_1 = torch.Tensor([[1, 4]])

tensor_2 = torch.Tensor([[1, -2], [3, 2]])

In [ ]:
tensor_1

tensor([[1., 4.]])

In [ ]:
tensor_2

tensor([[ 1., -2.],
        [ 3.,  2.]])

In [ ]:
tensor_3 = torch.randn([4,2])
tensor_3

tensor([[-0.8113,  0.5573],
        [-0.1378, -0.1526],
        [ 0.7082,  1.2665],
        [-0.6188,  0.5379]])

In [ ]:
#Transposta
tensor_3.T

tensor([[-0.8113, -0.1378,  0.7082, -0.6188],
        [ 0.5573, -0.1526,  1.2665,  0.5379]])

In [ ]:
#Transposta da Transposta
tensor_3.T.T

tensor([[-0.8113,  0.5573],
        [-0.1378, -0.1526],
        [ 0.7082,  1.2665],
        [-0.6188,  0.5379]])

In [ ]:
#Multiplicação matricial
## tensor_1 dimensao: [1,2]
## tensor_2 dimensao: [2,2]
tensor_1 * tensor_2

tensor([[ 1., -8.],
        [ 3.,  8.]])

In [ ]:
#Multiplicação tensor_1 x tensor_2
 ## o numero de colunas do primeiro tem que ser igual ao numero de linhas do segundo vetor


tensor_1 * tensor_2


tensor([[ 1., -8.],
        [ 3.,  8.]])

## **Gradientes e Autograd**

In [ ]:
x = torch.Tensor([2.0])

In [ ]:
x.dtype

torch.float32

In [ ]:
x.requires_grad = True

In [ ]:
x

tensor([2.], requires_grad=True)

In [ ]:
y = x**3
y

tensor([8.], grad_fn=<PowBackward0>)

In [ ]:
''' grad_fn - gradient function'''
# essa impressao n faz calculo do gradiente

' grad_fn - gradient function'

In [ ]:
# é diferente disto aqui:
torch.Tensor([2])**3

tensor([8.])

$f(x) = x^3$

$\frac{d f(x)}{dx} = 3x^2 = 3(2)^2 = 12$

In [ ]:
#como fazer para o pytorch calcular o gradiente:
#pegar o tensor resultaonte
y.backward()

In [ ]:
y

tensor([8.], grad_fn=<PowBackward0>)

In [ ]:
x.grad

tensor([12.])

## **Rede Neural Simples**

####**Criação dos Dados**

In [ ]:
inputs = torch.tensor([[0.0, 0.0], [0.0, 1.0], [1.0, 0.0], [1.0, 1.0]])
targets = torch.tensor([[0.0], [1.0], [1.0], [0.0]])

In [ ]:
inputs.shape

In [ ]:
inputs

####**Criação dos Modelo**

In [ ]:
targets

tensor([[0.],
        [1.],
        [1.],
        [0.]])

In [ ]:
targets.shape

torch.Size([4, 1])

In [ ]:
#Montando o modelo de rede neural
import torch.nn as nn #Neural network
import torch.optim as optim #optimazer

In [ ]:
#aqui necessita um pouco de Programação Orientada a Objeto
## em que preciso reescrever a função do Modelo para a minha rede neural
#aqui temos que ter cuidado pois entre as camadas precisa dar uma automatizada, o que é diferente do keras
class Model(nn.Module):
  def __init__(self): #criando as camadas, deixando-as compatíveis (saída de uma e entrada de outra)
    super().__init__() #inicializando o modelo
    self.fully_connected_1 = nn.Linear(in_features = 2, #criação da rede neural de entrada - quero 2 features do meu problema (relacionada as colunas dos inputs) e saindo 2 neuronios/features
                                  out_features = 2)
    self.fully_connected_2 = nn.Linear(in_features = 2, # a entrada dessa rede deve ter os mesmos neuronois da saida anterior
                         out_features = 1)  # a saida dessa camada tem que ser a mesma que da saida target

  def forward(self, input_tensor): #correlacionando os dados com as camdas criadas
    output_1 = self.fully_connected_1(input_tensor) #isso aqui faz com que o tensor x passe na primeira camada, dando um output
    output_2 = torch.relu(output_1) #pego a resposta do dado que passou na primeira camada e jogo na função de ativação
    output_3 = self.fully_connected_2(output_2)
    return output_3


    #output_10 = self.fully_connected_10(torch.cat(output_9, output_2) #aqui estou fazendo um bypass de uma camapda 9 para a 2) - SIM É possível! Chama-se COnexaoResidual
    #Isto pode ser feito com essa possibilidade de criar o objeto


####**Instanciação do modelo**

In [ ]:
torch.manual_seeds(42) #para garantir que o modelo está gerando os mesmos resultados
model = Model()
model

AttributeError: module 'torch' has no attribute 'manual_seeds'

In [ ]:
#O pytorch n tem o modulo sumario nativo, sendo necessario baixá-lo,

%%capture
!pip install torch-summary
from torchsummary import summary



In [ ]:
summary(model)

Layer (type:depth-idx)                   Param #
├─Linear: 1-1                            6
├─Linear: 1-2                            3
Total params: 9
Trainable params: 9
Non-trainable params: 0


Layer (type:depth-idx)                   Param #
├─Linear: 1-1                            6
├─Linear: 1-2                            3
Total params: 9
Trainable params: 9
Non-trainable params: 0

In [ ]:
'''
Por erro no colab está sendo impresso 2x a mesma info. (é possível verificar ali em cima)
'''

####**Criação da função de perda e do otimizador**

No keras n precisamos criar a função de perda e otimizadora, já no pytorch precisamos criá-las!

In [ ]:
[i for i in model.parameters()]

[Parameter containing:
 tensor([[-0.4949,  0.5829],
         [ 0.1165,  0.2315]], requires_grad=True),
 Parameter containing:
 tensor([-0.2082,  0.0250], requires_grad=True),
 Parameter containing:
 tensor([[-0.1093,  0.5502]], requires_grad=True),
 Parameter containing:
 tensor([0.5039], requires_grad=True)]

In [ ]:
loss_function = nn.MSELoss() #vamos usar MSELoss pois se trata de um problema de regressao,
optimizer = optim.Adam(  # este otimizador é um dos melhores que têm. SGD é o basico estocastico
    params = model.parameters(),
    lr = 0.01
    )


#o otimizador é uma regra para atualizar o peso, que depende do gradiente e função de perda
#o params faz com que o modelo facilite a otimização -

#Treinar modelo é variar os pesos

####**Treinamento do modelo**

In [ ]:
#no keras era suficiente fazer o .fit pra treinar o modelo, o que já n acontece aqui no pytorch!

# Algoritmo de retroprogapação (que será feito abaixo):
  # Passo 1) pegamos o dado, passamos pelo modelo para obter uma  do modelo (forward pass)
  # Passo 2) comparamos o resultado obtido com o resultado esperado
  # Passo 3) calculando a função de perda (loss function)
  # Passo 4) calculo do gradiente da função de perda
  # Passo 5) voltar atualizando os pesos da rede

#É isso que será feito abaixo! (retropropagação)

In [ ]:
for epoch in range(200):

  predicted = model(inputs) #joga os inputs no meu modelo e armazena no predicted (Passo 1)
  loss = loss_function(predicted, targets) # só mensura o erro da função perda (Passo 3)
  loss.backward() # calcula o gradiente da função perda (Passo 4)
  optimizer.step() #volta atualizando os pesos da rede (Passo 5) - Backward Pass
  optimizer.zero_grad() #zera o gradiente todas as vezes que ele vai sendo treinado

  if (epoch+1) % 10 == 0:
      print(f'epoch {epoch+1}, loss: {loss.item()}')

epoch 10, loss: 0.2783317565917969
epoch 20, loss: 0.2783317565917969
epoch 30, loss: 0.2783317565917969
epoch 40, loss: 0.2783317565917969
epoch 50, loss: 0.2783317565917969
epoch 60, loss: 0.2783317565917969
epoch 70, loss: 0.2783317565917969
epoch 80, loss: 0.2783317565917969
epoch 90, loss: 0.2783317565917969
epoch 100, loss: 0.2783317565917969
epoch 110, loss: 0.2783317565917969
epoch 120, loss: 0.2783317565917969
epoch 130, loss: 0.2783317565917969
epoch 140, loss: 0.2783317565917969
epoch 150, loss: 0.2783317565917969
epoch 160, loss: 0.2783317565917969
epoch 170, loss: 0.2783317565917969
epoch 180, loss: 0.2783317565917969
epoch 190, loss: 0.2783317565917969
epoch 200, loss: 0.2783317565917969


In [ ]:
#Pra rodar novamente o modelo, preciso instanciar novamnete (que nem no keras!)
#aiííí eu treino novamente o modelo, isso ocorre pois o otimizador está vinculado aos dados do modelo antigo.
# aííí eu preciso rodar novamente a parte que criei o otimizador!!! Isso vai vincular o otimizador ao novo modelo!
#no keras n precisa essa vinculação com o otimzador

In [ ]:
inputs_test = inputs[:2]
target_test = targets[:2]

In [ ]:
#Exemplo de como rodar o modelo novamente!

model = Model()
model

# ROdando novamente o otimizador e função de perda

loss_function = nn.MSELoss()
optimizer = optim.Adam(
    params = model.parameters(),
    lr = 0.01
    )


In [ ]:
# e se eu quiser ver a função de perda em um dataset de teste (que seria a validação)

for epoch in range(200):

  predicted = model(inputs) #joga os inputs no meu modelo e armazena no predicted (Passo 1)
  loss = loss_function(predicted, targets) # só mensura o erro da função perda (Passo 3)
  loss.backward() # calcula o gradiente da função perda (Passo 4)
  optimizer.step() #volta atualizando os pesos da rede (Passo 5) - Backward Pass
  optimizer.zero_grad() #zera o gradiente todas as vezes que ele vai sendo treinado

  if (epoch+1) % 10 == 0:
      with torch.no_grad(): #ele executa operações antes e depois do contexto pra ele n calcular o gradiente! Deixa o input_test separado
        predicted_test = model(inputs_test)

      test_loss = loss_function(predicted_test, target_test)
      print(f'epoch {epoch+1}, loss: {loss.item()}, test lost : {test_loss.item()}')

epoch 10, loss: 0.8619349002838135, test lost : 0.8535953164100647
epoch 20, loss: 0.5320906043052673, test lost : 0.4902014136314392
epoch 30, loss: 0.3770068883895874, test lost : 0.2462429255247116
epoch 40, loss: 0.3528550863265991, test lost : 0.14173009991645813
epoch 50, loss: 0.34553253650665283, test lost : 0.12999071180820465
epoch 60, loss: 0.32885661721229553, test lost : 0.15242542326450348
epoch 70, loss: 0.31791016459465027, test lost : 0.17062067985534668
epoch 80, loss: 0.3093113303184509, test lost : 0.1724369376897812
epoch 90, loss: 0.3011528253555298, test lost : 0.166763037443161
epoch 100, loss: 0.2940874695777893, test lost : 0.16350921988487244
epoch 110, loss: 0.28789421916007996, test lost : 0.164747416973114
epoch 120, loss: 0.2824156582355499, test lost : 0.16811001300811768
epoch 130, loss: 0.27761614322662354, test lost : 0.17152456939220428
epoch 140, loss: 0.2734164297580719, test lost : 0.17465843260288239
epoch 150, loss: 0.2697516679763794, test lost